export const API_URL = 'http://localhost:4000';

export const MULTIPLE_CHOICE = 'MULTIPLE_CHOICE';
export const SHORT_TEXT = 'SHORT_TEXT';

export const DEFAULT_QUESTION_TYPE = SHORT_TEXT;
export const DEFAULT_QUESTION_REQUIRED = false;
export const DEFAULT_QUESTION_DESCRIPTION_ENABLED = false;
export const DEFAULT_QUESTION_DESCRIPTION = '';

export const LOAD_ASSESSMENT_SUCCESS = 'LOAD_ASSESSMENT_SUCCESS';
export const LOAD_QUESTION_TYPES_SUCCESS = 'LOAD_QUESTION_TYPES_SUCCESS';
export const SET_ACTIVE_QUESTION = 'SET_ACTIVE_QUESTION';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const LOAD_ACTION_HISTORY_SUCCESS = 'LOAD_ACTION_HISTORY_SUCCESS';
export const UNDO_LATEST_ACTION_SUCCESS = 'UNDO_LATEST_ACTION_SUCCESS';
